# Generated by Django 3.1.1 on 2020-10-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201006_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fees', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
