# Generated by Django 3.1.1 on 2020-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payement',
            field=models.BooleanField(default=True),
        ),
    ]
