# Generated by Django 3.1.1 on 2020-12-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orders_payement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='payement',
            new_name='payment',
        ),
    ]
